version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_midcourse_capstone
      MYSQL_USER: apiMidcourseCapstone
      MYSQL_PASSWORD: iAmAWeakPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
